### PR TITLE
fixes #235 duplicate credits

### LINKED ISSUE #235: hall of fame > duplicate credits entries
following #231 we could state that credits array content is duplicated

### PR DESCRIPTION
**Pull request by boly38**
This PR fixes #235 : no more duplicate credits

demo: https://boly38.gk.kumy.org/halloffame.php

(@kumy : please notice that rec DNS is not working)

### CODE REVIEW

**Comment by kumy** [comment]
Regarding dns, I ve started to change hostname to 'staging.geokrety.org' but not yet finished, sorry. Else the change looks good. Feel free to merge.

On January 8, 2019 1:18:02 PM GMT+01:00, Vandeputte Brice <notifications@github.com> wrote:
>This PR fixes #235 : no more duplicate credits
>
>demo: https://boly38.gk.kumy.org/halloffame.php
>
>
>(@kumy : please notice that rec DNS is not working)
>You can view, comment on, or merge this pull request online at:
>
>  https://github.com/geokrety/geokrety-website/pull/236
>
>-- Commit Summary --
>
>  * fixes #235 duplicate credits
>
>-- File Changes --
>
>    M website/__sentry.php (2)
>    M website/halloffame.php (10)
>    M website/smarty_start.php (2)
>
>-- Patch Links --
>
>https://github.com/geokrety/geokrety-website/pull/236.patch
>https://github.com/geokrety/geokrety-website/pull/236.diff
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/geokrety/geokrety-website/pull/236

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by boly38** [comment]
ok sure, no pb 
(build are red due to qa rec wrong target url / please ping me when finished to upd qa)

**Comment by kumy** [comment]
DNS fixed, and vhosts are now configured.

**Comment by boly38** [comment]
staging halloffame is in strange state .. do we have a way to clean template cache file without admin rights? or disable it for one query?
I dont remember var_dump of config'credits'.. will check that tomorrow

**Comment by kumy** [comment]
Sorry that was me trying to find the last import, see PR #240

**Pull request merged**
