### PR TITLE
Prepare next release

### PR DESCRIPTION
**Pull request by kumy**

### CODE REVIEW

**Comment by kumy** [comment]
It's deployed, congrats @boly38 !!!

**Comment by boly38** [comment]
just see, thanks to you too 👍😁👏

**Comment by kumy** [comment]
Do you think it's worth publishing some news about the new map implementation? @boly38 Would you announce it?

**Comment by boly38** [comment]
yep that's a good point. I will send you English and French first version by mail.

**Comment by kumy** [comment]
Maybe we can ask some friend for translation in Polish @filipsPL, German @lineflyer, Dutch @harrieklomp

**Comment by kumy** [comment]
@boly38 News published.

**Comment by boly38** [comment]
CoOl thanks 😀

**Pull request merged**
