### PR TITLE
Fix #221: Allow to define robots.txt file per domain

### LINKED ISSUE #221: prevent tests instance indexation
[search example](https://www.google.fr/search?ei=Ku_-W5XgCtCSa7aAqPgI&q=%22%D0%9D%D0%95+%D0%97%D0%90%D0%91%D0%A3%D0%94%D0%AC%D0%A2%D0%95+%D0%9E%D0%A2%D0%9C%D0%95%D0%A2%D0%98%D0%A2%D0%AC+%D0%95%D0%93%D0%9E+%D0%98%D0%97%D0%AA%D0%AF%D0%A2%D0%98%D0%95+%D0%98+%D0%97%D0%90%D0%9A%D0%9B%D0%90%D0%94%D0%9A%D0%A3%21%22&oq=%22%D0%9D%D0%95+%D0%97%D0%90%D0%91%D0%A3%D0%94%D0%AC%D0%A2%D0%95+%D0%9E%D0%A2%D0%9C%D0%95%D0%A2%D0%98%D0%A2%D0%AC+%D0%95%D0%93%D0%9E+%D0%98%D0%97%D0%AA%D0%AF%D0%A2%D0%98%D0%95+%D0%98+%D0%97%D0%90%D0%9A%D0%9B%D0%90%D0%94%D0%9A%D0%A3%21%22&gs_l=psy-ab.3..35i39.6197.6738..7401...0.0..0.67.130.2......0....1..gws-wiz.7biMa0DsPHw)
image

seems https://boly38.gk.kumy.org is indexed by google :)
Getting test site as google results introduce a lots of confusion for our users. :(

- [ ] Need to update `rec` and `boly38` deploy scripts to enforce a `robots.txt` file that prevent google indexation. [this old robots.txt version](https://github.com/geokrety/geokrety-website/blob/edf2d0b042bbfe511e10df5e03ba6c466e6dc0a2/website/robots.txt) could help as example.

### PR DESCRIPTION
**Pull request by kumy**
The implementation permit to use `/robots-files/*.txt` files as
substitution for `robots.txt` on a used domain basis.

If no file exists corresponding to domain, then the `default.txt`
file is served.

The downside of this implementation is that there is a duplicated
file for geokrety.org and www.geokrety.org domains :/ Does using
a symlink between thos two files will work when checkout in M$ os?

### CODE REVIEW

**Comment by boly38** [comment]
in fact..
- current branch state: `geokrety.org.txt` and `www.geokrety.org.txt` are same file allowing google robots


what do you think to keep only `geokrety.org.txt` ?
this way google will index only one domain and ignore the other one. This could prevent indexing 2 time the same content.

**Comment by kumy** [comment]
I agree, maybe we should force redirect www to base domain too

**Comment by boly38** [comment]
>redirect www to base domain
if third pary (ex. like c:geo) uses `www` : does they support redirect ?

**Comment by kumy** [comment]
They should (and I can check and fix for this case), we should contact other partners like all opencaching platforms.. I ll do. But I think we should merge with modification to www.geokrety.org.txt to deny indexing and process this case case in anpther issue.

On November 29, 2018 12:53:33 PM GMT+01:00, Vandeputte Brice <notifications@github.com> wrote:
>>redirect www to base domain
>if third pary (ex. like c:geo) uses `www` : does they support redirect
>?
>
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/geokrety/geokrety-website/pull/222#issuecomment-442806816

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by boly38** [comment]
tested with gkShell: OK 👍

**Pull request merged**
