### PR TITLE
Deploy to prod

### PR DESCRIPTION
**Pull request by kumy**

### CODE REVIEW

**Comment by boly38** [comment]
Travis is blocked on state "_Waiting for status to be reported_" ?
  (I restarted the build yesterday, no effet)

**Comment by kumy** [comment]
... But only for those kind of PR (merge master to prod)

**Comment by boly38** [comment]
reproduced :)

**Comment by boly38** [comment]
I don't know if you're awaiting something from me, but for me, I'm ok to merge. I let you merge on your next availability

**Comment by kumy** [comment]
Thanks for the reminder, I'll deploy tonight ;)

**Comment by boly38** [comment]
do we have server side error for 'recent move on the map' welcome page link ?

**Comment by kumy** [comment]
If sentry says nothing, then it should be fine, no?

**Comment by kumy** [comment]
So what cause you trouble is that the link on the main page is broken?

`google_static_logs.png` is not generated on fly but from [script](https://github.com/geokrety/geokrety-scripts/blob/1a1293b3008b4f974120f43ffac79ac45cfef802/mapa_statyczna_logow/ostatnie_logi.sh#L12)

**Comment by kumy** [comment]
Script doesn't authenticate to google api :( 

```
# curl "http://maps.googleapis.com/maps/api/staticmap?size=500x500&markers=size:small|50.89,20.63|54.93,41.40|53.24,39.97|53.97,38.54|53.97,38.54|53.97,38.54|53.97,38.54|53.97,38.54|53.97,38.54|53.97,38.54|53.97,38.54|53.97,38.54|53.97,38.54|53.97,38.54|53.97,38.54|51.39,13.30|43.44,6.74|48.04,7.56|48.64,-2.03|48.04,7.56|43.44,6.74|48.04,7.56|48.04,7.56|51.05,7.68|48.04,7.56|50.58,2.35|49.35,6.70|49.35,6.70|51.32,13.31|48.11,-1.68|48.11,-1.70|53.47,14.48|53.47,14.48|53.47,14.48|53.47,14.48|53.47,14.48|53.47,14.48|53.47,14.48|53.47,14.48|53.47,14.48|53.47,14.48|53.47,14.48|53.47,14.48|53.47,14.48|53.47,14.48|53.47,14.48|53.47,14.48|53.47,14.48|53.47,14.48|53.47,14.48|53.47,14.48|53.47,14.48|53.47,14.48|53.47,14.48|53.47,14.48|50.73,7.10|52.52,13.41|52.52,13.41|52.52,13.41|51.18,14.43|51.18,14.43|51.18,14.43|51.23,12.76|51.23,12.76|51.14,12.66|50.78,12.90|50.78,12.90|50.78,12.88|50.78,12.88|50.78,12.90|50.78,12.90|50.83,12.96|50.83,12.96|48.17,11.47|48.16,11.49|48.16,11.48|48.15,11.46|43.45,6.63|43.45,6.63|43.45,6.63|43.45,6.63|43.45,6.63|43.45,6.63|43.45,6.63|43.45,6.63|43.45,6.63|43.45,6.63|43.45,6.63|43.45,6.63|43.45,6.63|43.45,6.63|43.45,6.63|43.44,6.62|43.44,6.62|43.44,6.62|43.44,6.62|43.44,6.62|43.46,6.60|43.46,6.60|43.46,6.60|&sensor=false"
The Google Maps Platform server rejected your request. You must use an API key to authenticate each request to Google Maps Platform APIs. For additional information, please refer to http://g.co/dev/maps-no-accountroot@fc8b71504b94:/opt/geokrety/mapa_statyczna_logow
```

**Comment by kumy** [comment]
`google_static_logs.png` generation should be fixed. https://github.com/geokrety/geokrety-scripts/commit/acf01bed8443e7e977f9adf966c1153f519ad321

**Pull request merged**
