### PR TITLE
Update export.php

### PR DESCRIPTION
**Pull request by harrieklomp**
Update IP address ocnl

### CODE REVIEW

**Comment by boly38** [comment]
would be more easy to maintain (next ip change) by injecting konfig parameters

**Comment by kumy** [comment]
Agree with boly38. I wonder what's the purpose of the ip list. I have to check...

On June 14, 2018 8:32:51 PM GMT+02:00, Boly38 <notifications@github.com> wrote:
>would be more easy to maintain (next ip change) by injecting konfig
>parameters 
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/geokrety/geokrety-website/pull/101#issuecomment-397395389

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kumy** [comment]
And as a first step we should merge as is for the moment, no ?

On June 14, 2018 8:32:51 PM GMT+02:00, Boly38 <notifications@github.com> wrote:
>would be more easy to maintain (next ip change) by injecting konfig
>parameters 
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/geokrety/geokrety-website/pull/101#issuecomment-397395389

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kumy** [comment]
@harrieklomp Thanks!

New dedicated issue for the "config idea" :heart_eyes: #102

**Pull request merged**
