### PR TITLE
Fixes #278 rest trip json encoding non UTF8 content

### LINKED ISSUE #278: no trip on map for some geokrety
Following geokrety have a map issue : no icon on the map, why ?

- https://geokrety.org/konkret.php?id=60972&nocache
-- trip rest query result is 200 but with no body

TODO
- [x] talk about map (potential bad behavior / onto website, twitter, fb)
- [x] check csv and gpx results - seems ok
- [x] try to reproduce locally using 60972 as example - based on chars - failed to reproduce
- [x] try to reproduce locally using 60972 as example - based on ruchy data - *ok reproduced* (special thanks to @kumy for tools)

--

*reproduced with real data*
- trip rest `json_encode` where resulting `FALSE` with `JSON_ERROR_UTF8` as last json error.
- fix : add safe_json_encoder

### PR DESCRIPTION
**Pull request by boly38**
Fixes #278 rest trip json encoding non UTF8 content

### CODE REVIEW

**Comment by kumy** [comment]
@boly38 Feel free to merge, we'll deploy a quick fix

**Comment by boly38** [comment]
would like to double check on 'boly38.staging' but he won't update to the last commit?

**Comment by kumy** [comment]
I've manually launched the update. (I have an idea why auto update didn't worked, I've cleaned my dns zone yesterday :/)

**Comment by boly38** [comment]
seems update didn't work :'(

>commit 09ee453 onto https://boly38.staging.geokrety.org/konkret.php?id=60972&nocache

**Comment by kumy** [comment]
Yep autoupdate is currently broken.

On April 12, 2019 7:45:04 AM GMT+02:00, Vandeputte Brice <notifications@github.com> wrote:
>seems update didn't work :'(
>
>>commit 09ee453 onto
>https://boly38.staging.geokrety.org/konkret.php?id=60972&nocache
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/geokrety/geokrety-website/pull/279#issuecomment-482445444

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kumy** [comment]
Missing dns entry for auto-updater recreated. It should be working again in a moment…

**Comment by kumy** [comment]
@boly38 should we include this fix in pending release?

**Comment by boly38** [comment]
just would like to check staging env fix but can't

**Comment by kumy** [comment]
I've just launched update to `origin/boly38`. It's will be available in a few minutes.

**Comment by kumy** [comment]
https://boly38.staging.geokrety.org/konkret.php?id=60972&nocache is now working. Good job!

**Comment by boly38** [comment]
cool 👍

**Comment by kumy** [comment]
Did the auto deploy worked fine?

On April 13, 2019 6:37:42 PM GMT+02:00, Vandeputte Brice <notifications@github.com> wrote:
>Merged #279 into master.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/geokrety/geokrety-website/pull/279#event-2274216511

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by boly38** [comment]
yep i've checked boly38.staging and were ok.
once merged staging ok too
https://staging.geokrety.org/konkret.php?id=60972&nocache got his map 👍 many thanks @kumy

**Comment by kumy** [comment]
Feel free to create a merge commit to prod

On April 13, 2019 8:18:41 PM GMT+02:00, Vandeputte Brice <notifications@github.com> wrote:
>yep i've checked boly38.staging and were ok.>
>once merged staging ok too>
>https://staging.geokrety.org/konkret.php?id=60972&nocache got his map
>👍 many thanks @kumy>
>>
>-- >
>You are receiving this because you were mentioned.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/geokrety/geokrety-website/pull/279#issuecomment-482857308

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Pull request merged**
