### PR TITLE
Fix search pagination

### PR DESCRIPTION
**Pull request by edykim**
Related #145.

In the search form, form actions were combined GET/POST. All search form changed the action as GET so all variables pass through URL rather than form submit. It will fix the pagination issue.

### CODE REVIEW

**Comment by edykim** [comment]
I can suggest using GET request for the search form in general. Because GET requests can be bookmarked without issue and it doesn't interfere browser history so you can navigate with back and forward buttons.

**Comment by kumy** [comment]
Hum, I tend to agree with @edykim arguments, especially when it comes to browsing history and bookmark.

**Comment by kumy** [comment]
Let's merge and test on https://rec.geokrety.org

**Comment by kumy** [comment]
@edykim Thanks for your contribution!

**Pull request merged**
