### PR TITLE
WIP: Reformat the ruchy form using bootstrap

### PR DESCRIPTION
**Pull request by kumy**
Here is a proposition to reformat the `ruchy` page ("Log a GeoKret"). You can see it live at https://rec.geokrety.org/ruchy.php

I know it's not `responsive`, this will require to reformat the base layout and could be addressed later / another PR. I would like to display the `log type` selector as toggle buttons, I still have to work on it.

What do you think?

# Before

screenshot-2018-3-29 geokrety operations on geokrety-old

# After

screenshot-2018-4-2 geokrety signaler un geokret

### CODE REVIEW

**Comment by boly38** [comment]
To be faster, I put here my feedbacks, but I know that comment source would have been better ;)

positive feeback:  I like style, global design, error management

- top message:  WARN => INFO ? Red => Blue ?

- dictionnary:	J'ai "rencontré" un GéoKret : j'ai "vu"?  (help_generate.php?help=fr#Chooselogtype coherency)

- "2. Objet voyageur" issue : 2 red error icons (1 expected?)
- "3. Nouvel emplacement issue"

	Step1) input waypoint
	Step2) click on "Utiliser la géolocalisation internet"
	Then we can revert position and go back to "Waypoint" use ?

	(was already the case in previous version)

- "3. Nouvel emplacement" issue

	'name of cache' (en/fr??)

- "3. Nouvel emplacement" improvement

	use 'name of cache'  'Verifier' button
	Results are showed onthe right panel
	would be very great to have 2 links 
		1 link to the cache (we have already)
		1 link with cache CODE to fill the form with one click

- "4. Données supplémentaires" issue

	hover on "Nom" input text show a popup that is behind Date input

- "4. Données supplémentaires" issue

	commentaire "max length" (en/fr??)

----

out of review scope (improvements idea):
- (minor) improve datepicker style

**Comment by kumy** [comment]
@boly38 Issues #21 #22 #24 should now be fixed.

**Comment by kumy** [comment]
@boly38 here is the latest version https://rec.geokrety.org/ruchy.php . It look nice, isn't it?

**Comment by boly38** [comment]
completely fond of love with fresh new first section

**Pull request merged**
