### PR TITLE
feat: add new labels

### PR DESCRIPTION
**Pull request by okainov**
Add two new labels:
- One provided by one of our players
- One is modification of existing one to add QR code and move tracking code on the back of the label.

### CODE REVIEW

**Comment by okainov** [comment]
Unused parameters which Codacy complains about seem expected as we implement an interface and don't need those...

**Review by kumy — APPROVED** [review]
LGTM

**Comment by kumy** [comment]
Let's merge and test on [staging](https://staging.geokrety.org/).

Also could you provide the same templates for GKv2. In GKv2 templates are now `.svg` files. This [document](https://github.com/geokrety/geokrety-website/blob/feature/new-theme/CONTRIBUTING.label-templates.md) will help you to get started

**Comment by kumy** [comment]
@okainov `SchrottieTemplate2` need a fix, I have those errors:
```

Warning: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in /var/www/html/lib/labels/PngTemplate.php on line 6

Warning: file_get_contents(): Failed to enable crypto in /var/www/html/lib/labels/PngTemplate.php on line 6

Warning: file_get_contents(https://geokrety.org/templates/qr2/qr.php?d=https://geokrety.org/m/qr.php?nr=49W9D2): failed to open stream: operation failed in /var/www/html/lib/labels/PngTemplate.php on line 6

Warning: imagecreatefromstring(): Empty string or invalid image in /var/www/html/lib/labels/PngTemplate.php on line 6

Warning: imagecropauto() expects parameter 1 to be resource, boolean given in /var/www/html/lib/labels/PngTemplate.php on line 7

Warning: imagesx() expects parameter 1 to be resource, null given in /var/www/html/lib/labels/schrottie2/SchrottieTemplate2.php on line 28

Warning: imagesy() expects parameter 1 to be resource, null given in /var/www/html/lib/labels/schrottie2/SchrottieTemplate2.php on line 28

Warning: imagecopyresampled() expects parameter 2 to be resource, null given in /var/www/html/lib/labels/schrottie2/SchrottieTemplate2.php on line 28

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/lib/labels/PngTemplate.php:6) in /var/www/html/lib/labels/PngTemplate.php on line 14

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/lib/labels/PngTemplate.php:6) in /var/www/html/lib/labels/PngTemplate.php on line 16
```

**Comment by kumy** [comment]
And same for the other template

**Comment by kumy** [comment]
hum, it also happen on another untouched template (`Modern 2 :: Wallson`) so issue may not be related to this PR specifically

**Comment by kumy** [comment]
the fix from https://github.com/geokrety/geokrety-website/issues/670#ref-commit-efd7bb8 may be missing on staging for an obscure reason :eyes:

**Comment by kumy** [comment]
ok, I just had to update [branches on the other repo](https://github.com/geokrety/geokrety-website-docker-base/branches) :+1:

**Comment by okainov** [comment]
So should this be now in prod? I don't see it there... 

Works fine in staging though!

As for QR codes issue I've seen the same locally, probably something with certificates in the image, locally I workarounded it by using pre-generated static file and.

We'll take a look at new SVG labels, haven't seen it before, good point, thanks!

**Comment by kumy** [comment]
> So should this be now in prod? I don't see it there...

It should but is not. I saw that this morning and plan to check/fix tonight.

Thanks for the contribs!

**Pull request merged**
