### PR TITLE
Fixes #278 trip utf8 to prod

### LINKED ISSUE #278: no trip on map for some geokrety
Following geokrety have a map issue : no icon on the map, why ?

- https://geokrety.org/konkret.php?id=60972&nocache
-- trip rest query result is 200 but with no body

TODO
- [x] talk about map (potential bad behavior / onto website, twitter, fb)
- [x] check csv and gpx results - seems ok
- [x] try to reproduce locally using 60972 as example - based on chars - failed to reproduce
- [x] try to reproduce locally using 60972 as example - based on ruchy data - *ok reproduced* (special thanks to @kumy for tools)

--

*reproduced with real data*
- trip rest `json_encode` where resulting `FALSE` with `JSON_ERROR_UTF8` as last json error.
- fix : add safe_json_encoder

### PR DESCRIPTION
**Pull request by boly38**
- Fixes #278 rest trip json encoding non UTF8 content

### CODE REVIEW

**Comment by boly38** [comment]
seems master is already based on prod (following github network vue)
Simply clicking on 'Rebase and merge' will fast forward I think.
If this is true, I don't understand your reminder. Do I miss something?
(I m on phone)

**Comment by kumy** [comment]
I like to see the branching when merging to prod. I typically:
* merge such PR using "Merge pull request". It create explicitly a merge commit
* then on my computer, `git checkout master` `git fetch` `git rebase origine/prod`

I understand what you said with FF method, but (I feel personally) that it will be more difficult to see by which step the prod passed. And… yes honnestly this is the purpose of tags :(
Screenshot from 2019-04-13 22-34-30

Also FF will rewrite commits history and change commits ids. Both, commiter and merger will have the double picture in GH history. 
Screenshot from 2019-04-13 22-38-39




Do you prefer us to merge FF and tag after each merge?

**Comment by kumy** [comment]
> merge such PR using "Merge pull request". It create explicitly a merge commit
I do this only when merging from `master` to `prod`

When merging `some PR` to `master`, I use FF. (Expecting the PR to be already rebased by commiter)

**Comment by boly38** [comment]
I understand your process and don't want to change it. yep merge is a pretty way to natively see prod steps without tagging. ok

As I can't do the second step right now, I let you do, or else will do tomorrow or monday. :)

**Comment by kumy** [comment]
I can finish the process if you wish, or let you do when when you can, as an exercise. Please let me know.

**Comment by boly38** [comment]
I let you do the master rebase then. thanks for your time 👍

**Pull request merged**
