### PR TITLE
Deploy to prod

### PR DESCRIPTION
**Pull request by kumy**

### CODE REVIEW

**Comment by kumy** [comment]
Did a quick review, I think we're ready to release

**Comment by kumy** [comment]
Done.

**Comment by boly38** [comment]
cool 😁🤸

but seems like the gkcredits array content is duplicated?
https://geokrety.org/halloffame.php


maybe config to check?

**Comment by kumy** [comment]
Hum, problem exists on other staging environment too. I have check and didn't found any spefic config on server side (ie: no override of this array). From what I see, problem comes from the multiple loading of `templates/konfig.php`. First one from `__sentry.php`, secnod from `smarty_start.php`.

We should think about checking and don't load `konfig` multiple times, or at least use `require_once`??

**Pull request merged**
