### PR TITLE
Fix #519: Check Dockerfile using github actions

### LINKED ISSUE #519: test for Dockerfile syntax
add a step that will check Dockerfile syntax 
- locally (cf makefile)
- and on travis

### PR DESCRIPTION
**Pull request by kumy**
What about using a GitHub Action for this?

https://github.com/marketplace/actions/docker-lint

I've enabled it for the other repo https://github.com/geokrety/geokrety-website-docker-cron Seems to do the job…

There are 43 available actions https://github.com/actions, not sure what else can help us…

### CODE REVIEW

**Comment by kumy** [comment]
Unfortunately, the `HEALTHCHECK` command is not yey understood by `dockerfilelint` https://github.com/replicatedhq/dockerfilelint/issues/28

**Comment by boly38** [comment]
First thanks to try github action, one thing I had in mind and I've never done.

Arg I see .. 3 years old issue, on this repo with poor activity..

If I look into their code, it seems that parser is "home made", so hard to maintain/improve ..

**Comment by kumy** [comment]
PR replicatedhq/dockerfilelint/117 is now merged. I'm wondering when it will be available in Github actions ;)

**Comment by kumy** [comment]
Commit rebased, but check is still failing :(

**Comment by kumy** [comment]
Let's try with version `1.1.1`

**Comment by kumy** [comment]
I've setup `pre-commit` hook some days ago, let's use this instead of this uncontrollable github actions thing :tired_face:

**Pull request merged**
